### ISSUE TITLE
How to remove installed fonts and color schemes

### ISSUE THREAD

**Issue by Llewellyn500** [blackc8/termux-style#2]
I can't see any way to remove the font and the color from my termux terminal. I've tried the remove option but the theme still stays on. Pls provide a way to revert all the settings to the default. Or if there is a way can you show it.

**Comment by blackc8** [comment]
The remove option is already in the home.
But you can also remove it from command line arhus
```
style --remove
```
Hope this helps

**Comment by blackc8** [comment]
I hope Reinstalling termux-style this time will fix all your problems

**Comment by Llewellyn500** [comment]
Didn't work. The font and color I applied are still applied.

**Comment by blackc8** [comment]
That means you want to remove the font and colors not termux-style the commad i gave you remove termux-style from your termux to remove the font use comamnd
```
rm ~/.termux/font.ttf
```
to remove the color use
```
rm ~/.termux/colors.properties

**Comment by Llewellyn500** [comment]
Thank you. Works like a charm. I'll be waiting for the next version. Also may I make a video on it.

**Comment by blackc8** [comment]
Yes obviously you can make, I will glad to have a video on my repo.Thanks for your effort

**Comment by Llewellyn500** [comment]
OK I will when I'm done. Hop to see the version 2 soon. 😊

**Comment by blackc8** [comment]
Done my jobe the I added the set to default option in both colors and fonts section . Its your turn now

**Comment by Llewellyn500** [comment]
OK. I'll start making the video but it will be live next week. This week's videos have already been scheduled

**Comment by Llewellyn500** [comment]
Just tested the script, everything works perfectly. Thank you for the great script.

**Comment by blackc8** [comment]
I have other repos too like termux-lock, slowloris, mailr ,etc you can use them too

**Comment by Llewellyn500** [comment]
OK I'll try them out

**Comment by Llewellyn500** [comment]
I've sent you a link through email. Go check it out.

**Comment by blackc8** [comment]
Thank you a lot to appreciate my work with your I will there too whenever you need me.😀

**Comment by Llewellyn500** [comment]
OK I will
